### ISSUE TITLE
前端交接后登陆验证存在bug

### ISSUE THREAD

**Issue by lpxofbuaa** [BUAASoftwareEngineering/vLab-Frontend#11]
- logout的时候没有跳转到login页面
- 未登录时能够访问home页面，（写了跳转拦截语句但是有bug）
- 登陆了再次访问时仍需要登陆（同上）
- 建议在http response之前加上spin组件，提示用户正在加载
- 建议弹出窗口提示使用iview的组件，不要用alert

**Comment by ZfWan-Hub** [comment]
完成bug修复
