### ISSUE TITLE
问题反馈帖

### ISSUE THREAD

**Issue by NSun-S** [BUAASoftwareEngineering/vLab-Frontend#53]

**Comment by Hokah** [comment]
visual lab online使用体验很好，页面简洁，操作简单，赞

**Comment by 503680421** [comment]
调试控制台使用时候会出现指令光标陷入页面底部的情况（多条指令执行直至占满控制台完成后），通过上下拉动，修改控制台页框高度可以重新复原
![QQ图片20200430122321](https://user-images.githubusercontent.com/47276003/80671872-b3f7fa00-8add-11ea-9e1c-0897b87ab7d1.png)

**Comment by NSun-S** [comment]
编辑器右键菜单可能将标签页顶上去，导致显示异常

**Comment by NSun-S** [comment]
菜单栏下拉菜单需要滚轮操作
